-- Consolidated Database Schema (DDL)

-- Sequences
CREATE SEQUENCE IF NOT EXISTS scheduled_employee_shift_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS schedule_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS employee_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS position_group_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS category_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS category_group_id_seq START WITH 100000;

-- Core Tables
CREATE TABLE company (
  company_id INTEGER PRIMARY KEY,
  company_name VARCHAR(255),
  department_name VARCHAR(255),
  address VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(255),
  timestamp TIMESTAMP DEFAULT NOW(),
  timezone FLOAT,
  status VARCHAR(255),
  trial_start DATE,
  drop_dead DATE,
  price_table INTEGER,
  tos VARCHAR(255),
  week_start_day INTEGER DEFAULT 1
);

CREATE TABLE employee (
  employee_id INTEGER PRIMARY KEY DEFAULT nextval('employee_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  status VARCHAR(255),
  last_logon TIMESTAMP,
  logon_count INTEGER DEFAULT 0,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  employee_number VARCHAR(255),
  email VARCHAR(255),
  hire_date TIMESTAMP DEFAULT NOW(),
  max_scheduled_hours INTEGER,
  max_daily_hours INTEGER,
  pay_rate FLOAT,
  emp_type_id INTEGER,
  max_weekly_days INTEGER,
  max_daily_shifts INTEGER,
  comments TEXT,
  priority_group VARCHAR(255),
  google_cal_export BOOLEAN DEFAULT FALSE,
  next_alert_date DATE,
  custom_field_1 VARCHAR(255),
  custom_field_2 VARCHAR(255),
  employee_photo VARCHAR(255),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  accessibility_mode BOOLEAN DEFAULT FALSE,
  username VARCHAR(255)
);

CREATE TABLE employee_phone (
  employee_id INTEGER NOT NULL REFERENCES employee(employee_id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL,
  phone_number TEXT NOT NULL,
  PRIMARY KEY (employee_id, sort_order)
);

CREATE TABLE employee_address (
    employee_id INTEGER PRIMARY KEY REFERENCES employee(employee_id) ON DELETE CASCADE,
    address VARCHAR(255),
    address2 VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip VARCHAR(20)
);

CREATE TABLE schedule (
  schedule_id INTEGER PRIMARY KEY DEFAULT nextval('schedule_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  is_published BOOLEAN DEFAULT FALSE,
  description VARCHAR(255),
  start_date DATE,
  day_of_week SMALLINT,
  timestamp TIMESTAMP DEFAULT NOW(),
  last_change TIMESTAMP DEFAULT NOW(),
  archived VARCHAR(255)
);

-- Renamed skill to position
CREATE TABLE position (
  position_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  description VARCHAR(255),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  timestamp TIMESTAMP DEFAULT NOW()
);

-- Renamed skill_group to position_group
CREATE TABLE position_group (
  group_id INTEGER PRIMARY KEY DEFAULT nextval('position_group_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  description VARCHAR(255),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE group_position (
  group_id INTEGER NOT NULL REFERENCES position_group(group_id),
  position_id INTEGER NOT NULL REFERENCES position(position_id),
  PRIMARY KEY (group_id, position_id)
);

CREATE TABLE category (
  category_id INTEGER PRIMARY KEY DEFAULT nextval('category_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  short_desc VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  start_time VARCHAR(255),
  end_time VARCHAR(255),
  position_id INTEGER REFERENCES position(position_id),
  color SMALLINT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT chk_category_short_desc_not_blank CHECK (btrim(short_desc) <> '')
);

CREATE TABLE cat_group (
  group_id INTEGER PRIMARY KEY DEFAULT nextval('category_group_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  description VARCHAR(255),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE group_cat (
  group_id INTEGER NOT NULL REFERENCES cat_group(group_id),
  cat_id INTEGER NOT NULL REFERENCES category(category_id),
  PRIMARY KEY (group_id, cat_id)
);

CREATE TABLE scheduled_employee (
  shift_id INTEGER PRIMARY KEY DEFAULT nextval('scheduled_employee_shift_id_seq'),
  employee_id INTEGER REFERENCES employee(employee_id),
  schedule_id INTEGER REFERENCES schedule(schedule_id),
  company_id INTEGER REFERENCES company(company_id),
  description VARCHAR(255),
  start_time TIME,
  end_time TIME,
  duration FLOAT,
  is_overnight BOOLEAN DEFAULT FALSE,
  required_position_id INTEGER REFERENCES position(position_id),
  category_id INTEGER REFERENCES category(category_id),
  color VARCHAR(255),
  is_deleted BOOLEAN DEFAULT FALSE,
  changed_by INTEGER REFERENCES employee(employee_id)
);

CREATE TABLE employee_position (
  employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
  position_id INTEGER NOT NULL REFERENCES position(position_id),
  suitability_level INTEGER,
  preference VARCHAR(255),
  pay_rate FLOAT,
  cert_date DATE,
  PRIMARY KEY (employee_id, position_id)
);

-- Security/User Tables
CREATE TABLE emp_type (
    emp_type_id SERIAL PRIMARY KEY,
    emp_type_name VARCHAR(100) UNIQUE NOT NULL
);

ALTER TABLE employee
  ADD CONSTRAINT fk_employee_emp_type
  FOREIGN KEY (emp_type_id) REFERENCES emp_type(emp_type_id);

CREATE TABLE user_roles (
    role_id SERIAL PRIMARY KEY,
    role_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    user_login_id VARCHAR(255) UNIQUE NOT NULL,
    user_login_pw VARCHAR(255) NOT NULL,
    company_id INTEGER REFERENCES company(company_id),
    emp_type_id INTEGER REFERENCES emp_type(emp_type_id),
    role_id INTEGER REFERENCES user_roles(role_id),
    employee_id INTEGER REFERENCES employee(employee_id),
    encryption_type INTEGER,
    login_failures INTEGER DEFAULT 0
);

CREATE TABLE manager_permissions (
    permission_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    is_main_manager BOOLEAN DEFAULT FALSE,
    can_add_shifts BOOLEAN DEFAULT FALSE,
    can_import_templates BOOLEAN DEFAULT FALSE,
    can_upload_shifts BOOLEAN DEFAULT FALSE,
    can_autofill_shifts BOOLEAN DEFAULT FALSE,
    can_clear_schedules BOOLEAN DEFAULT FALSE,
    can_edit_shifts BOOLEAN DEFAULT FALSE,
    can_save_templates BOOLEAN DEFAULT FALSE,
    can_publish_schedules BOOLEAN DEFAULT FALSE,
    can_unpublish_schedules BOOLEAN DEFAULT FALSE,
    can_manage_categories BOOLEAN DEFAULT FALSE,
    can_add_employees BOOLEAN DEFAULT FALSE,
    can_view_pay_rates BOOLEAN DEFAULT FALSE,
    can_edit_employees BOOLEAN DEFAULT FALSE,
    can_approve_trades BOOLEAN DEFAULT FALSE,
    can_approve_time_off BOOLEAN DEFAULT FALSE,
    can_change_company_settings BOOLEAN DEFAULT FALSE,
    can_manage_positions BOOLEAN DEFAULT FALSE,
    can_manage_team_members BOOLEAN DEFAULT FALSE,
    can_receive_manager_notifications BOOLEAN DEFAULT FALSE
);

CREATE TABLE employee_list_config (
    config_id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES company(company_id),
    column_name VARCHAR(255) NOT NULL,
    is_visible BOOLEAN DEFAULT TRUE,
    UNIQUE(company_id, column_name)
);

-- Preferences Tables
CREATE TABLE day_prefs (
    employee_id INT NOT NULL REFERENCES employee(employee_id),
    date DATE NOT NULL,
    prefs CHAR(96),
    compression INT,
    edited_by INT REFERENCES employee(employee_id),
    is_day_prefs BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (employee_id, date)
);

CREATE TABLE week_prefs (
    employee_id INT NOT NULL REFERENCES employee(employee_id),
    start_date DATE NOT NULL,
    prefs CHAR(672),
    compression INT,
    edited_by INT REFERENCES employee(employee_id),
    PRIMARY KEY (employee_id, start_date)
);

CREATE TABLE time_off_request (
    request_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id INTEGER NOT NULL REFERENCES company(company_id),
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    day_count INTEGER DEFAULT 1,
    requested_at TIMESTAMP DEFAULT NOW(),
    status VARCHAR(32) NOT NULL,
    comments VARCHAR(500),
    is_full_day BOOLEAN DEFAULT FALSE,
    repeat_count INTEGER DEFAULT 1
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_schedule_start_date ON schedule (start_date);
CREATE INDEX idx_se_company_schedule ON scheduled_employee(company_id, schedule_id);
CREATE INDEX idx_se_company_employee ON scheduled_employee(company_id, employee_id);
CREATE INDEX idx_employee_company_id ON employee(company_id);
CREATE UNIQUE INDEX idx_employee_company_email ON employee (company_id, email)
WHERE email IS NOT NULL AND is_deleted = FALSE;
CREATE INDEX idx_position_company_id ON position(company_id);
CREATE INDEX idx_category_company_id ON category(company_id);
CREATE INDEX idx_time_off_company_employee ON time_off_request(company_id, employee_id);
CREATE INDEX idx_time_off_company_status ON time_off_request(company_id, status);

-- ============================================================
-- Row Level Security
-- Policy expression on every tenant table:
--   current_setting('app.current_tenant', true)::INTEGER = company_id
--   OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
--
-- missing_ok=true → returns NULL (not error) when GUC is absent;
-- NULL::INTEGER ≠ any company_id, so access is denied safely by default.
--
-- Set on every connection by TenantAwareDataSource (TenantDatabaseConfig.java).
-- Bypass (tenant=0) flows through app.internal_system_lookup='true'.
--
-- Tables intentionally WITHOUT RLS (global/auth-side):
--   emp_type, user_roles, users, manager_permissions
-- ============================================================

-- Direct company_id tables

ALTER TABLE company ENABLE ROW LEVEL SECURITY;
ALTER TABLE company FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON company
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE employee ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON employee
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON schedule
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE position ENABLE ROW LEVEL SECURITY;
ALTER TABLE position FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON position
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE position_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE position_group FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON position_group
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE category ENABLE ROW LEVEL SECURITY;
ALTER TABLE category FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON category
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE cat_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE cat_group FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON cat_group
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE scheduled_employee ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_employee FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON scheduled_employee
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

-- Indirect tenant tables (no direct company_id; tenant resolved via FK join)

ALTER TABLE employee_phone ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_phone FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON employee_phone
  USING (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = employee_phone.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = employee_phone.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE employee_address ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_address FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON employee_address
  USING (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = employee_address.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = employee_address.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE employee_position ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_position FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON employee_position
  USING (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = employee_position.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = employee_position.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE group_position ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_position FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON group_position
  USING (
    EXISTS (
      SELECT 1 FROM position_group pg
      WHERE pg.group_id = group_position.group_id
        AND pg.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM position_group pg
      WHERE pg.group_id = group_position.group_id
        AND pg.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE group_cat ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_cat FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON group_cat
  USING (
    EXISTS (
      SELECT 1 FROM cat_group cg
      WHERE cg.group_id = group_cat.group_id
        AND cg.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM cat_group cg
      WHERE cg.group_id = group_cat.group_id
        AND cg.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE day_prefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE day_prefs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON day_prefs
  USING (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = day_prefs.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = day_prefs.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE week_prefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE week_prefs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON week_prefs
  USING (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = week_prefs.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employee e
      WHERE e.employee_id = week_prefs.employee_id
        AND e.company_id = current_setting('app.current_tenant', true)::INTEGER
    )
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE employee_list_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_list_config FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON employee_list_config
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );

ALTER TABLE time_off_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_off_request FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON time_off_request
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );
