-- Consolidated Database Schema (DDL) snapshot

-- Sequences
CREATE SEQUENCE IF NOT EXISTS scheduled_employee_shift_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS schedule_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS employee_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS position_group_id_seq START WITH 100000;
CREATE SEQUENCE IF NOT EXISTS category_group_id_seq START WITH 100000;

-- Core Tables
CREATE TABLE company (
  company_id INTEGER PRIMARY KEY,
  company_name VARCHAR(255),
  department_name VARCHAR(255),
  address VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(255),
  timestamp TIMESTAMP DEFAULT NOW(),
  timezone FLOAT,
  status VARCHAR(255),
  trial_start DATE,
  drop_dead DATE,
  price_table INTEGER,
  tos VARCHAR(255)
);

CREATE TABLE employee (
  employee_id INTEGER PRIMARY KEY DEFAULT nextval('employee_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  status VARCHAR(255),
  last_logon TIMESTAMP,
  logon_count INTEGER DEFAULT 0,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  employee_number VARCHAR(255),
  email VARCHAR(255),
  hire_date TIMESTAMP DEFAULT NOW(),
  max_scheduled_hours INTEGER,
  max_daily_hours INTEGER,
  pay_rate FLOAT
);

CREATE TABLE employee_phone (
  employee_id INTEGER NOT NULL REFERENCES employee(employee_id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL,
  phone_number TEXT NOT NULL,
  PRIMARY KEY (employee_id, sort_order)
);

CREATE TABLE schedule (
  schedule_id INTEGER PRIMARY KEY DEFAULT nextval('schedule_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  is_published BOOLEAN DEFAULT FALSE,
  description VARCHAR(255),
  start_date DATE,
  day_of_week SMALLINT,
  timestamp TIMESTAMP DEFAULT NOW(),
  last_change TIMESTAMP DEFAULT NOW(),
  archived VARCHAR(255)
);

CREATE TABLE position (
  position_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  description VARCHAR(255),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE position_group (
  group_id INTEGER PRIMARY KEY DEFAULT nextval('position_group_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  description VARCHAR(255),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE group_position (
  group_id INTEGER NOT NULL REFERENCES position_group(group_id),
  position_id INTEGER NOT NULL REFERENCES position(position_id),
  PRIMARY KEY (group_id, position_id)
);

CREATE TABLE category (
  category_id INTEGER PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  short_desc VARCHAR(255),
  description VARCHAR(255),
  start_time VARCHAR(255),
  end_time VARCHAR(255),
  position_id INTEGER REFERENCES position(position_id),
  color SMALLINT,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE cat_group (
  group_id INTEGER PRIMARY KEY DEFAULT nextval('category_group_id_seq'),
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  description VARCHAR(255),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE group_cat (
  group_id INTEGER NOT NULL REFERENCES cat_group(group_id),
  cat_id INTEGER NOT NULL REFERENCES category(category_id),
  PRIMARY KEY (group_id, cat_id)
);

CREATE TABLE scheduled_employee (
  shift_id INTEGER PRIMARY KEY DEFAULT nextval('scheduled_employee_shift_id_seq'),
  employee_id INTEGER REFERENCES employee(employee_id),
  schedule_id INTEGER REFERENCES schedule(schedule_id),
  company_id INTEGER REFERENCES company(company_id),
  description VARCHAR(255),
  start_time TIME,
  end_time TIME,
  duration FLOAT,
  is_overnight BOOLEAN DEFAULT FALSE,
  required_position_id INTEGER REFERENCES position(position_id),
  category_id INTEGER REFERENCES category(category_id),
  color VARCHAR(255),
  is_deleted BOOLEAN DEFAULT FALSE,
  changed_by INTEGER REFERENCES employee(employee_id)
);

CREATE TABLE employee_position (
  employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
  position_id INTEGER NOT NULL REFERENCES position(position_id),
  suitability_level INTEGER,
  preference VARCHAR(255),
  pay_rate FLOAT,
  cert_date DATE,
  PRIMARY KEY (employee_id, position_id)
);

CREATE TABLE emp_type (
    emp_type_id SERIAL PRIMARY KEY,
    emp_type_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE user_roles (
    role_id SERIAL PRIMARY KEY,
    role_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    user_login_id VARCHAR(255) UNIQUE NOT NULL,
    user_login_pw VARCHAR(255) NOT NULL,
    company_id INTEGER REFERENCES company(company_id),
    emp_type_id INTEGER REFERENCES emp_type(emp_type_id),
    role_id INTEGER REFERENCES user_roles(role_id),
    employee_id INTEGER REFERENCES employee(employee_id),
    encryption_type INTEGER,
    login_failures INTEGER DEFAULT 0
);

CREATE TABLE manager_permissions (
    permission_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    is_main_manager BOOLEAN DEFAULT FALSE,
    can_add_shifts BOOLEAN DEFAULT FALSE,
    can_import_templates BOOLEAN DEFAULT FALSE,
    can_upload_shifts BOOLEAN DEFAULT FALSE,
    can_autofill_shifts BOOLEAN DEFAULT FALSE,
    can_clear_schedules BOOLEAN DEFAULT FALSE,
    can_edit_shifts BOOLEAN DEFAULT FALSE,
    can_save_templates BOOLEAN DEFAULT FALSE,
    can_publish_schedules BOOLEAN DEFAULT FALSE,
    can_unpublish_schedules BOOLEAN DEFAULT FALSE,
    can_manage_categories BOOLEAN DEFAULT FALSE,
    can_add_employees BOOLEAN DEFAULT FALSE,
    can_view_pay_rates BOOLEAN DEFAULT FALSE,
    can_edit_employees BOOLEAN DEFAULT FALSE,
    can_approve_trades BOOLEAN DEFAULT FALSE,
    can_approve_time_off BOOLEAN DEFAULT FALSE,
    can_change_company_settings BOOLEAN DEFAULT FALSE,
    can_manage_positions BOOLEAN DEFAULT FALSE,
    can_manage_team_members BOOLEAN DEFAULT FALSE,
    can_receive_manager_notifications BOOLEAN DEFAULT FALSE
);

CREATE TABLE day_prefs (
    employee_id INT NOT NULL REFERENCES employee(employee_id),
    date DATE NOT NULL,
    prefs CHAR(96),
    compression INT,
    edited_by INT REFERENCES employee(employee_id),
    is_day_prefs BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (employee_id, date)
);

CREATE TABLE week_prefs (
    employee_id INT NOT NULL REFERENCES employee(employee_id),
    start_date DATE NOT NULL,
    prefs CHAR(672),
    compression INT,
    edited_by INT REFERENCES employee(employee_id),
    PRIMARY KEY (employee_id, start_date)
);

CREATE TABLE time_off_request (
  request_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  day_count INTEGER DEFAULT 1,
  requested_at TIMESTAMP DEFAULT NOW(),
  status VARCHAR(32) NOT NULL,
  comments VARCHAR(500),
  is_full_day BOOLEAN DEFAULT FALSE,
  repeat_count INTEGER DEFAULT 1
);

CREATE TABLE time_off_request (
  request_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id INTEGER NOT NULL REFERENCES company(company_id),
  employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  day_count INTEGER DEFAULT 1,
  requested_at TIMESTAMP DEFAULT NOW(),
  status VARCHAR(32) NOT NULL,
  comments VARCHAR(500),
  is_full_day BOOLEAN DEFAULT FALSE,
  repeat_count INTEGER DEFAULT 1
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_schedule_start_date ON schedule (start_date);
CREATE INDEX idx_se_company_schedule ON scheduled_employee(company_id, schedule_id);
CREATE INDEX idx_se_company_employee ON scheduled_employee(company_id, employee_id);
CREATE INDEX idx_employee_company_id ON employee(company_id);
CREATE INDEX idx_position_company_id ON position(company_id);
CREATE INDEX idx_category_company_id ON category(company_id);
CREATE INDEX idx_time_off_company_employee ON time_off_request(company_id, employee_id);
CREATE INDEX idx_time_off_company_status ON time_off_request(company_id, status);
