spring.datasource.url=jdbc:postgresql://localhost:5432/w2wdb
spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/w2wdb
spring.datasource.username=${APP_DB_USERNAME:w2wuser_app}
spring.datasource.password=${APP_DB_PASSWORD:w2wpass_pass}
spring.flyway.url=${FLYWAY_DB_URL:${spring.datasource.url}}
spring.flyway.user=${FLYWAY_DB_USERNAME:w2wuser}
spring.flyway.password=${FLYWAY_DB_PASSWORD:w2wpass}
