spring.datasource.url=jdbc:postgresql://localhost:5432/w2wdb
spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/w2wdb
spring.datasource.username=w2wuser
spring.datasource.password=w2wpass
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
