spring.datasource.url=${DEV_DB_JDBC_URL}://${DEV_DB_URL}
spring.datasource.jdbc-url=${DEV_DB_JDBC_URL}://${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
spring.flyway.url=${DEV_FLYWAY_DB_URL:${spring.datasource.url}}
spring.flyway.user=${DEV_FLYWAY_DB_USERNAME:${spring.datasource.username}}
spring.flyway.password=${DEV_FLYWAY_DB_PASSWORD:${spring.datasource.password}}
