spring.datasource.url=${DEV_DB_JDBC_URL}://${DEV_DB_URL}
spring.datasource.jdbc-url=${DEV_DB_JDBC_URL}://${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
