spring.datasource.driverClassName=org.postgresql.Driver
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${APP_SHOW_SQL:true}
spring.jpa.open-in-view=false

spring.flyway.enabled=true

jwt.keystore.path=classpath:w2w-keystore.p12
jwt.keystore.password=w2wpass
jwt.keystore.alias=w2w-jwt
jwt.key.password=w2wpass
jwt.expiration-ms=${JWT_EXPIRATION_MS:1800000}
