apiVersion: v1
kind: Secret
metadata:
  name: when-to-work-backend-secret
  namespace: platformai
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: dev
  DEV_DB_URL: 54.82.188.74:5442/when2work
  DEV_DB_JDBC_URL: jdbc:postgresql
  DEV_DB_USERNAME: when2work
  DEV_DB_PASSWORD: xxxxxxxxx
