CREATE TABLE time_off_request (
    request_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id INTEGER NOT NULL REFERENCES company(company_id),
    employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    day_count INTEGER DEFAULT 1,
    requested_at TIMESTAMP DEFAULT NOW(),
    status VARCHAR(32) NOT NULL,
    comments VARCHAR(500),
    is_full_day BOOLEAN DEFAULT FALSE,
    repeat_count INTEGER DEFAULT 1
);

CREATE INDEX idx_time_off_company_employee ON time_off_request(company_id, employee_id);
CREATE INDEX idx_time_off_company_status ON time_off_request(company_id, status);
CREATE INDEX idx_time_off_company_dates ON time_off_request(company_id, start_date, end_date);

ALTER TABLE time_off_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_off_request FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON time_off_request
  USING (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  )
  WITH CHECK (
    current_setting('app.current_tenant', true)::INTEGER = company_id
    OR current_setting('app.internal_system_lookup', true)::TEXT = 'true'
  );