ALTER TABLE skill DROP COLUMN IF EXISTS status;
ALTER TABLE skill ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE skill ALTER COLUMN skill_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('skill', 'skill_id'),
    COALESCE((SELECT MAX(skill_id) FROM skill), 1),
    EXISTS(SELECT 1 FROM skill)
);
